ec2_keypair: "reema"
ec2_security_group: "sg-05ae33a58df34225c"
ec2_instance_type: "t2.micro"
ec2_image: "ami-0bdb1d6c15a40392c"
ec2_subnet_ids: ['subnet-9009e7ca','subnet-c478d7a2','subnet-e89f23a0']
ec2_region: "eu-west-1"
ec2_tag_Name: "Testserver"
ec2_tag_Type: "Testserver"
ec2_tag_Environment: "production"
ec2_volume_size: 16