---
 - ec2:
    key_name: "{{ ec2_keypair }}"
    group_id: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    vpc_subnet_id: "{{ ec2_subnet_ids|random }}"
    region: "{{ ec2_region }}"
    instance_tags: '{"Name":"{{ec2_tag_Name}}","Type":"{{ec2_tag_Type}}","Environment":"{{ec2_tag_Environment}}"}'
    assign_public_ip: yes
    wait: yes
    count: 1
   register: ec2

 - add_host:
    hostname : "{{ item.public_ip }}"
    groups: apache
    ansible_ssh_private_key_file: /etc/ansible/reema.pem
    ansible_user: ec2-user
   with_items: "{{ ec2.instances }}"

 - wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 10
    timeout: 320
    state: started
   with_items: "{{ ec2.instances }}"

 - s3:
    bucket: reema-demo
    object: ca.crt
    dest: /usr/local/ca.crt
    mode: get

 - s3:
    bucket: reema-demo
    object: ca.key
    dest: /usr/local/ca.key
    mode: get